#!/bin/sh

pkg install \
    zsh git curl terraform ripgrep jq jo gmake htop gnupg fzf \
        pngcrush neofetch ipcalc closure-compiler postgresql14-client \
        docker ImageMagick7 sqlite3 ffmpeg kubectl bat \
        syslog-ng unbound \
        ruby go erlang rust elixir \
        vim emacs \
        xorg i3 i3status rofi \
        firefox chromium weechat \
        spotify-qt spotifyd \
        gimp inkscape libreoffice audacity obs-studio \
        portfmt portlint \
        vm-bhyve grub2-bhyve linux_base-c7 \
        1password-client2 transmission

sysrc sendmail_enable="NONE"

sysrc clear_tmp_enable=YES

sysrc dumpdev=AUTO

sysrc ntpd_enable=YES

sysrc moused_enable=YES

sysrc linux_enable=YES

sysrc spotifyd_enable=YES

sysrc pf_enable=YES
sysrc pflog_enable=YES

sysrc cloned_interfaces=bridge0
sysrc ifconfig_bridge0_name=vnet0
sysrc ifconfig_vnet0="inet 172.16.2.1/24 addm net0 up descr vm"

sysrc gateway_enable=YES

sysrc kld_list="vmm"

sysrc vm_enable=YES
sysrc vm_dir="zfs:zroot/usr/vm"
sysrc vm_list="docker"
sysrc vm_delay="5"

sysrc syslog_ng_enable="YES"
sysrc syslogd_enable="NO"

install -m 644 -o gearnode -g gearnode files/curlrc $HOME/.curlrc
install -m 644 -o gearnode -g gearnode files/curlrc $HOME/.curlrc
install -m 644 -o gearnode -g gearnode files/gemrc $HOME/.gemrc
install -m 644 -o gearnode -g gearnode files/gitconfig $HOME/.gitconfig
install -m 644 -o gearnode -g gearnode files/gitignore $HOME/.gitignore
install -m 644 -o gearnode -g gearnode files/iex.exs $HOME/.iex.exs
install -m 644 -o gearnode -g gearnode files/mailcap $HOME/.mailcap
install -m 644 -o gearnode -g gearnode files/ripgreprc $HOME/.ripgreprc
install -m 644 -o gearnode -g gearnode files/zshrc $HOME/.zshrc

mkdir -p $HOME/.config
mkdir -p $HOME/.config/i3
mkdir -p $HOME/.config/i3status

install -m 644 -o gearnode -g gearnode files/i3/config $HOME/.config/i3/config
install -m 644 -o gearnode -g gearnode files/i3status/config $HOME/.config/i3status/config

mkdir -p $HOME/.ssh
install -m 644 -o gearnode -g gearnode files/ssh_config $HOME/.ssh/config
