#!/bin/sh

sysrc hostname="workstation.frimin.fr"

sysrc ifconfig_igc0_name="net0"
sysrc ifconfig_net0="DHCP"
sysrc ifconfig_net0_ipv6="inet6 accept_rtadv"

sysrc ifconfig_re0_name="net1"
sysrc ifconfig_ext1="DHCP"
sysrc ifconfig_ext1_ipv6="inet6 accept_rtadv"

install -m 644 -o gearnode -g gearnode pf.conf /etc/pf.conf
install -m 644 -o gearnode -g gearnode Xdefaults $HOME/.Xdefaults
