#!/bin/sh

sysrc hostname="workstation.frimin.fr"

sysrc ifconfig_igc0_name="net0"
sysrc ifconfig_net0="DHCP"
sysrc ifconfig_net0_ipv6="inet6 accept_rtadv"

sysrc ifconfig_re0_name="net1"
sysrc ifconfig_ext1="DHCP"
sysrc ifconfig_ext1_ipv6="inet6 accept_rtadv"

cp pf.conf /etc/pf.conf
cp Xdefaults $HOME/.Xdefaults
