#!/usr/bin/env sh

set -eu

usage() {
    cat <<EOF
Standard commands
link            create symbolic links
version         dot tool version
help            display help
EOF
}

version() {
    echo "dot 1.0.0.alpha  18 Mar 2020"
}

link() {
    local file dir

    dir="$(pwd)"
    file="$1"

    ln -fs $dir/$file $HOME/.$file
}

link_all() {
    # git
    link gitconfig
    link gitignore

    # sh
    link zshrc

    # ruby
    link gemrc
    link irbrc
    link pryrc

    # psql
    link psqlrc
    link pg_service.conf

    # curl
    link curlrc

    # ag
    link agignore

    # elixir
    link iex.exs
}

command="help"
if [ $# -ge 1 ]; then
    command="$1"
fi

case "$command" in
    "link")
        link_all ;;
    "version")
        version
        exit 0 ;;
    "help")
        usage
        exit 0 ;;
    *)
        fatal "invalid command '$1'; type help for a list" ;;
esac
