#!/usr/bin/env sh

set -eu

root=$(dirname $0)
. $root/common

usage() {
    cat <<EOF
Usage: $0 OPTIONS

OPTIONS

 -h     display help
EOF
}

link() {
    local file

    file="$1"

    ln -fs $root/$file $HOME/.$file
}

# git
link gitconfig
link gitignore

# sh
link zshrc

# ruby
link gemrc
link irbrc
link pryrc

# psql
link psqlrc
link pg_service.conf

# curl
link curlrc

# ag
link agignore

# elixir
link iex.exs
