#!/bin/sh

echo "\033[34m==>\033[0m check brew presence"
if test ! $(which brew) ; then
  echo -e "\033[32mInstalling Homebrew\033[0m"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo -e "\033[32mInstalling Cask\033[0m"
  brew install caskroom/cask/brew-cask
else
  echo "\033[34m==>\033[0m already install"
fi
